name: personal_webpage
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^11.0.0
  url_launcher: ^6.3.1
  tw_chat:
    path: packages/tw_chat
  tw_primitives:
    path: packages/tw_primitives
  tw_keywords:
    path: packages/tw_keywords
  flutter_svg: ^2.3.0
  web: ^1.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/t1_logo/t1_logo.svg
    - lib/subjects/index.json
    - lib/subjects/Terese/keywords.md
    - lib/subjects/Terese/professional_story.md

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito/Nunito[wght].ttf
        - asset: assets/fonts/nunito/Nunito-Italic[wght].ttf
          style: italic
    - family: ComingSoon
      fonts:
        - asset: assets/fonts/comingsoon/ComingSoon-Regular.ttf
          weight: 400
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/bebasneue/BebasNeue-Regular.ttf
          weight: 400

