name: tw_chat
description: Internal chat module for the personal_webpage Flutter app.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  web: ^1.1.1
  url_launcher: ^6.3.1
  super_editor: ^0.3.0-dev.51
  tw_flutter_skin:
    path: ../../packages/tw_flutter_skin

dependency_overrides:
  super_editor:
    path: ../../packages/super_editor_local

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
